version: '3.4'

services:
  user-services:
    image: user-services
    container_name: user-services
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - star-network

networks:
  star-network:
    external:
      name: star-network