version: '3.4'

services:
  user-worker:
    image: user-worker
    container_name: user-worker
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    networks:
      - star-network

networks:
  star-network:
    external:
      name: star-network